# Generated by Django 5.2.3 on 2025-06-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
